<?php
/**
 * SalesDesk — Sitemap: Static & Marketing Pages
 * Route: /sitemap-static.xml
 *
 * Every URL here is a fixed route (not driven by a DB table). Adding a
 * new static page to the site means adding one line here.
 *
 * NOTE: the /cars-for-sale/ browse root, its curated condition/body_type
 * facet pages, and the per-make landing pages used to live in this
 * file. They've moved to sitemap/cars-for-sale.php (which now also
 * owns the paginated car-detail rows previously generated by
 * cars.php), via the shared smCarsForSaleExtras() helper in
 * sitemap-functions.php. That keeps every /cars-for-sale/... URL
 * — curated or per-car — coming from a single generator, so the
 * curated-facet list can't drift out of sync with
 * includes/seo-canonical.php the way it could when this file and
 * cars.php each maintained their own copy.
 */

declare(strict_types=1);

require_once '../includes/security.php';
require_once '../includes/database.php';
require_once '../includes/functions.php';
require_once 'includes/sitemap-functions.php';

applyCachePolicy('public');

$xml = smCached('sitemap-static', SITEMAP_CACHE_TTL, function (): string {
    $base = smBaseUrl();
    $now  = date('c');

    // path => url class (drives priority/changefreq — see smPolicy())
    $pages = [
        '/'                              => 'home',

        '/desks/'                        => 'directory',
        '/news/'                         => 'directory',
        '/outreach/'                     => 'info',
        '/how-it-works/brokers.php'      => 'info',
        '/how-it-works/dealers.php'      => 'info',
        '/how-it-works/sales-exec.php'   => 'info',
        '/brokers.php'                   => 'info',
        '/dealers.php'                   => 'info',
        '/tools/compare/'                => 'info',
        '/tools/finance-calculator/'     => 'info',
        '/privacy'                       => 'legal',
        '/terms'                         => 'legal',
    ];

    $out = smUrlsetOpen();
    foreach ($pages as $path => $class) {
        $p = smPolicy($class);
        $out .= smEmitUrl($base . $path, $now, $p['changefreq'], $p['priority']);
    }

    $out .= smUrlsetClose();
    return $out;
});

smOutput($xml);
